[versions]
agp = "8.13.2"
kotlin = "2.3.0"
android-minSdk = "24"
android-compileSdk = "36"
maven-publish = "0.35.0"
composeMultiplatform = "1.9.3"
androidx-activityCompose = "1.12.2"
material3 = "1.9.0"
kotlinxCoroutinesCore = "1.10.2"

[libraries]
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
