[versions]
agp = "9.0.0"
foundation = "1.10.0"
kotlin = "2.3.0"
android-minSdk = "24"
android-compileSdk = "36"
android-targetSdk = "36"
logger = "1.2.0"
maven-publish = "0.36.0"
composeMultiplatform = "1.10.0"
androidx-activityCompose = "1.12.3"
material3 = "1.9.0"

[libraries]
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
logger = { module = "io.github.shivathapaa:logger", version.ref = "logger" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
